/*
 * This source file was generated by the Gradle 'init' task
 */
package jdbc;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.time.OffsetDateTime;

import org.flywaydb.core.Flyway;

import jdbc.persistence.ConnectionUtil;
import jdbc.persistence.EmployeeDAO;
import jdbc.persistence.EmployeeParamDAO;
import jdbc.persistence.entity.EmployeeEntity;


public class Main{
	
	public final static EmployeeParamDAO employeeDAO = new EmployeeParamDAO();  // Utilizando a classe segura.
	
	//public final static EmployeeDAO employeeDAO = new EmployeeDAO(); 
	
    public static void main(String [] args) {
    	
    	// Usar para limpar o flyway, caso queira ler todas as migrações do zero.
    	/*var flyway = Flyway.configure()
    			.dataSource("jdbc:mysql://localhost:3306/databasedio", "root", "senhaSGBD")
    		    .cleanDisabled(false) // HABILITA O CLEAN
    		    .load();
    		flyway.clean();*/
    	
    	var flyway = Flyway.configure()
    			.dataSource("jdbc:mysql://localhost:3306/databasedio", "root", "senhaSGBD")
    			.load();
    	flyway.migrate();
    	
    	
    	// A nova classe com segurança permite inserir o caracter aspas simples. Com a outra daria erro
    	var insert = new EmployeeEntity();
	    insert.setName("Marta'");  
	    insert.setSalary(new BigDecimal("10500"));
	    insert.setBirthday(OffsetDateTime.now().minusYears(40));
    	System.out.println(insert);
    	employeeDAO.insert(insert);
    	System.out.println(insert);
    	
    	
    	//employeeDAO.findAll().forEach(System.out::println);
    	
    	//System.out.println(employeeDAO.findById(1));
    	
    	/*var update = new EmployeeEntity();
    	update.setId(1); 
    	update.setName("Maria"); 
    	update.setSalary(new BigDecimal("10500"));
    	update.setBirthday(OffsetDateTime.now().minusYears(18).minusDays(3)); 
    	employeeDAO.update(update); */
    	
    	//employeeDAO.delete(2);
   	
  
    }
}